[package]
name = "crudder-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Parser for the Crudder DSL"

[dependencies]
crudder-ast.workspace = true
crudder-lexer.workspace = true
ariadne.workspace = true
thiserror.workspace = true
